<?php

$page_title = 'Flora Marcos Ono';
require('header.php');
require_once ('nav.php');

echo '
<header class="jumbotron">
  <h1 class="text-center">Conheça a minha história</h1>
  <p class="text-center">Da area rural a grande cidade</p>
</header>
<article class="container">
    <h1 class="text-center">Titulo</h1>
    <p>Integer turpis nisi, accumsan quis ultrices at, volutpat sed enim. Sed eu enim ut lacus fringilla ornare vel et leo. In ac arcu a dui rhoncus sollicitudin sed nec purus. Sed fermentum gravida velit, in tempor mi mattis luctus. Pellentesque egestas egestas dolor id lacinia. Ut tristique a turpis nec convallis. Mauris elit orci, sagittis quis mi eu, finibus mollis tortor. Ut fermentum ultrices dui sit amet hendrerit. Donec nunc libero, faucibus ac interdum a, iaculis et eros. Donec accumsan venenatis risus quis tincidunt. Nulla vulputate est eget elit sollicitudin, sed suscipit est cursus. Cras id leo id velit mollis venenatis nec eget risus. </p>
    <img src="images/aue.jpg" class="pull-left col-md-6">
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse bibendum, nunc quis laoreet iaculis, turpis magna sagittis nisi, at finibus arcu odio ut dolor. Aenean velit nulla, aliquet quis mauris non, finibus mollis enim. Donec nec augue fermentum, dignissim eros eu, facilisis neque. Aenean euismod venenatis ipsum, et tempor ligula aliquam non. Ut quis justo metus. Aliquam aliquam nunc nec erat bibendum dignissim. Mauris tempor, diam sit amet interdum tempor, purus tellus porttitor ante, at luctus magna ex non nulla. Donec et tortor ut lorem efficitur vehicula. Mauris quam augue, ultricies vel erat eleifend, rutrum venenatis nisl. Duis ultricies porttitor enim rhoncus fringilla. Nunc auctor imperdiet sem vel condimentum. Phasellus eleifend lectus ut nulla finibus tempus. Ut ullamcorper egestas tellus, nec iaculis ex dapibus eu. Donec facilisis sit amet nisi in venenatis. Etiam ut magna ante. </p>
    <p>Etiam nec est vitae dolor ornare pulvinar. Integer at enim ac lacus efficitur accumsan eu a tortor. Mauris ornare ultricies egestas. Praesent porttitor consectetur dolor, et scelerisque sem malesuada at. Nulla imperdiet aliquam nibh, sit amet rutrum urna tincidunt sit amet. Integer id sodales ipsum, quis tincidunt neque. Etiam elementum sapien id eros scelerisque, eu convallis nibh lobortis. Nullam at turpis non lacus ullamcorper luctus. Curabitur placerat eros ut arcu condimentum pulvinar. In bibendum magna eu massa faucibus, vel pharetra nibh rutrum. Integer iaculis ornare ex. </p>
    <p>Duis sollicitudin convallis velit. Sed sagittis et magna et cursus. Morbi nec posuere sem. Fusce posuere lorem quam, vel porta justo gravida in. Nullam et placerat sem. Etiam porttitor, orci non dapibus placerat, nunc est tincidunt libero, tristique viverra leo eros vitae ligula. Praesent fringilla ex sit amet tortor cursus, in volutpat arcu semper. Duis accumsan sagittis placerat. Morbi justo magna, varius sed finibus id, vestibulum ac tortor. Nunc quis nunc ligula. Fusce condimentum elit felis, vel pharetra purus dignissim placerat. Etiam condimentum diam pulvinar, mollis metus eget, placerat arcu. </p>
    <img src="images/phantom.jpg" class="pull-right col-md-6">
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse bibendum, nunc quis laoreet iaculis, turpis magna sagittis nisi, at finibus arcu odio ut dolor. Aenean velit nulla, aliquet quis mauris non, finibus mollis enim. Donec nec augue fermentum, dignissim eros eu, facilisis neque. Aenean euismod venenatis ipsum, et tempor ligula aliquam non. Ut quis justo metus. Aliquam aliquam nunc nec erat bibendum dignissim. Mauris tempor, diam sit amet interdum tempor, purus tellus porttitor ante, at luctus magna ex non nulla. Donec et tortor ut lorem efficitur vehicula. Mauris quam augue, ultricies vel erat eleifend, rutrum venenatis nisl. Duis ultricies porttitor enim rhoncus fringilla. Nunc auctor imperdiet sem vel condimentum. Phasellus eleifend lectus ut nulla finibus tempus. Ut ullamcorper egestas tellus, nec iaculis ex dapibus eu. Donec facilisis sit amet nisi in venenatis. Etiam ut magna ante. </p>
    <p>Etiam nec est vitae dolor ornare pulvinar. Integer at enim ac lacus efficitur accumsan eu a tortor. Mauris ornare ultricies egestas. Praesent porttitor consectetur dolor, et scelerisque sem malesuada at. Nulla imperdiet aliquam nibh, sit amet rutrum urna tincidunt sit amet. Integer id sodales ipsum, quis tincidunt neque. Etiam elementum sapien id eros scelerisque, eu convallis nibh lobortis. Nullam at turpis non lacus ullamcorper luctus. Curabitur placerat eros ut arcu condimentum pulvinar. In bibendum magna eu massa faucibus, vel pharetra nibh rutrum. Integer iaculis ornare ex. </p>
    <p>Duis sollicitudin convallis velit. Sed sagittis et magna et cursus. Morbi nec posuere sem. Fusce posuere lorem quam, vel porta justo gravida in. Nullam et placerat sem. Etiam porttitor, orci non dapibus placerat, nunc est tincidunt libero, tristique viverra leo eros vitae ligula. Praesent fringilla ex sit amet tortor cursus, in volutpat arcu semper. Duis accumsan sagittis placerat. Morbi justo magna, varius sed finibus id, vestibulum ac tortor. Nunc quis nunc ligula. Fusce condimentum elit felis, vel pharetra purus dignissim placerat. Etiam condimentum diam pulvinar, mollis metus eget, placerat arcu. </p>
  
</article>
';
require_once ('footer.php');
?>